name: ${DOCKER_PROJECT_NAME:-docker-dbs}

services:
    mysql:
        container_name: ${DOCKER_MYSQL_CONTAINER_NAME:-mysql}
        image: mysql:${DOCKER_MYSQL_VERSION}
        ports:
            - 127.0.0.1:${MYSQL_EXT_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ${DOCKER_MYSQL_VOLUME:-mysql_volume_local}:/var/lib/mysql
        restart: always
    postgres:
        container_name: ${DOCKER_POSTGRES_CONTAINER_NAME:-postgres}
        image: postgres:${DOCKER_POSTGRES_VERSION}
        ports:
            - 127.0.0.1:${POSTGRES_EXT_PORT:-5432}:5432
        expose:
            - 5432
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        volumes:
            - ${DOCKER_POSTGRES_VOLUME:-postgres_volume_local}:/var/lib/postgresql/data
        restart: always

    pgadmin:
        container_name: ${DOCKER_PGADMIN_CONTAINER_NAME:-pgadmin}
        image: dpage/pgadmin4:${DOCKER_PGADMIN_VERSION}
        ports:
            - 127.0.0.1:${PGADMIN_EXT_PORT:-8080}:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        volumes:
            - ${DOCKER_PGADMIN_VOLUME:-pgadmin_volume_local}:/var/lib/pgadmin
        restart: always

    mongo:
        container_name: ${DOCKER_MONGO_CONTAINER_NAME:-mongo}
        image: mongo:${DOCKER_MONGO_VERSION}
        ports:
            - 127.0.0.1:${MONGO_EXT_PORT:-27017}:27017
        volumes:
            - ${DOCKER_MONGO_VOLUME:-mongo_volume_local}:/data/db
        expose:
            - 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        restart: always

volumes:
    mysql_volume_local:
    postgres_volume_local:
    mongo_volume_local:
    pgadmin_volume_local:
