services:
    postgres:
        container_name: ${DOCKER_POSTGRES_CONTAINER_NAME}
        image: postgres:${DOCKER_POSTGRES_VERSION}
        ports:
            - 127.0.0.1:${POSTGRES_EXT_PORT}:5432
        expose:
            - 5432
        networks:
            - shared
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        volumes:
            - postgres_volume:/var/lib/postgresql/data
            - ../initdb/postgres.sh:/docker-entrypoint-initdb.d/postgres.sh
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

volumes:
    postgres_volume:

networks:
    shared:
        name: ${DOCKER_NETWORK_NAME}
        external: true