services:
    postgres:
        container_name: ${DOCKER_POSTGRES_CONTAINER_NAME}
        image: postgres:${DOCKER_POSTGRES_VERSION}
        ports:
            - 127.0.0.1:${POSTGRES_EXT_PORT}:5432
        expose:
            - 5432
        networks:
            - shared
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        restart: always

volumes:
    postgres_volume:

networks:
    shared:
        name: ${DOCKER_NETWORK_NAME}
        external: true