services:
    mysql:
        container_name: ${DOCKER_MYSQL_CONTAINER_NAME}
        image: mysql:${DOCKER_MYSQL_VERSION}
        ports:
            - 127.0.0.1:${MYSQL_EXT_PORT}:3306
        networks:
            - shared
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - mysql_volume:/var/lib/mysql
        restart: always

volumes:
    mysql_volume:

networks:
    shared:
        name: ${DOCKER_NETWORK_NAME}
        external: true