services:
    mongoexprs:
        container_name: ${DOCKER_MONGOEXPRS_CONTAINER_NAME}
        image: mongo-express:${DOCKER_MONGOEXPRS_VERSION}
        ports:
            - 127.0.0.1:${MONGOEXPRS_EXT_PORT}:8081
        networks:
            - shared
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${DOCKER_MONGO_CONTAINER_NAME}:27017/
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRS_PASSWORD}
            ME_CONFIG_MONGODB_PORT: ${MONGO_EXT_PORT}
            ME_CONFIG_MONGODB_SERVER: ${DOCKER_MONGO_CONTAINER_NAME}
        depends_on:
            - mongo
        volumes:
            - mongoexprs_volume:/data/db
        restart: always

volumes:
    mongoexprs_volume:

networks:
    shared:
        name: ${DOCKER_NETWORK_NAME}
        external: true