services:
    mongo:
        container_name: ${DOCKER_MONGO_CONTAINER_NAME}
        image: mongo:${DOCKER_MONGO_VERSION}
        ports:
            - 127.0.0.1:${MONGO_EXT_PORT}:27017
        volumes:
            - mongo_volume:/data/db
        expose:
            - 27017
        networks:
            - shared
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        restart: always

volumes:
    mongo_volume:

networks:
    shared:
        name: ${DOCKER_NETWORK_NAME}
        external: true
